[project]
authors = ["Morteza Ansarinia <ansarinia@me.com>"]
channels = ["conda-forge"]
description = "StudyFlow Modeler"
name = "studyflow"
platforms = [ "osx-arm64" ]
version = "0.1.0"

[tasks]

[dependencies]
nodejs = ">=22.12.0,<22.13"
