[project]
authors = ["Morteza Ansarinia <ansarinia@me.com>"]
channels = ["conda-forge"]
description = "Studyflow Modeler"
name = "studyflow"
platforms = [ "osx-arm64" ]
version = "0.1.0"

[tasks]

[dependencies]
nodejs = "<24"
