# Generated by packages/cli/scripts/release.mjs — do not edit by hand.
class Studyflow < Formula
  desc "Command-line tool and desktop app for studyflow diagrams"
  homepage "https://github.com/behaverse/studyflow-modeler"
  # No `version`: Homebrew scans 26.10.2 out of the release url, and audit calls a second copy redundant.
  license "MIT"
  # `studyflow run --runtime local` drives the skills in libexec with uv.
  depends_on "uv"

  on_macos do
    on_arm do
      url "https://github.com/behaverse/studyflow-modeler/releases/download/v26.10.2/studyflow-26.10.2-darwin-arm64.tar.gz"
      sha256 "542e9ca27e8eb5941b21b6d16135fea73da4b1cd742b52a2fed0f65b6f17ed7d"
    end
    on_intel do
      url "https://github.com/behaverse/studyflow-modeler/releases/download/v26.10.2/studyflow-26.10.2-darwin-x64.tar.gz"
      sha256 "5047c8596ad7d1d5c912c705377926822ad86f5ae0c7047eac5d1f5fa0b10f89"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/behaverse/studyflow-modeler/releases/download/v26.10.2/studyflow-26.10.2-linux-arm64.tar.gz"
      sha256 "5fd12a410369dd9aa3815fa933b9d5a5e69161820494bd65bfc0771325b5103c"
    end
    on_intel do
      url "https://github.com/behaverse/studyflow-modeler/releases/download/v26.10.2/studyflow-26.10.2-linux-x64.tar.gz"
      sha256 "42ed59a12f2ab2b78938625369b6345f29c726a38bf2a3e5509b085a70938daf"
    end
  end

  def install
    bin.install "studyflow"
    # The skills, found from bin/studyflow as ../libexec/skills, and the runner SDK they import, as ../libexec/sdk.
    libexec.install "skills"
    libexec.install "sdk"
    # The desktop app, served by `studyflow edit` from ../libexec/ui.
    libexec.install "ui"
  end

  test do
    (testpath/"minimal.studyflow").write <<~YAML
      id: brew_test
      definitions:
        targetNamespace: http://bpmn.io/schema/bpmn
      Brew_Test:
        type: bpmn:Process
        name: Brew test
        flowElements:
          Start:
            type: bpmn:StartEvent
          Done:
            type: bpmn:EndEvent
    YAML
    assert_match version.to_s, shell_output("#{bin}/studyflow --version")
    assert_match "OK", shell_output("#{bin}/studyflow validate #{testpath}/minimal.studyflow")
    assert_match "Brew test", shell_output("#{bin}/studyflow info #{testpath}/minimal.studyflow")
    port = free_port
    pid = spawn bin/"studyflow", "edit", "--no-open", "--port", port.to_s, testpath/"minimal.studyflow"
    sleep 2
    assert_match "Studyflow", shell_output("curl -s http://127.0.0.1:#{port}/app")
    assert_match "Brew test", shell_output("curl -s http://127.0.0.1:#{port}/open/minimal.studyflow")
  ensure
    Process.kill("TERM", pid) if pid
  end
end
