# Generated by packages/cli/scripts/release.mjs — do not edit by hand.
class Studyflow < Formula
  desc "Command-line tool and desktop app for studyflow diagrams"
  homepage "https://github.com/behaverse/studyflow-modeler"
  # No `version`: Homebrew scans 26.9.23 out of the release url, and audit calls a second copy redundant.
  license "MIT"
  # `studyflow run --runtime local` drives the skills in libexec with uv.
  depends_on "uv"

  on_macos do
    on_arm do
      url "https://github.com/behaverse/studyflow-modeler/releases/download/v26.9.23/studyflow-26.9.23-darwin-arm64.tar.gz"
      sha256 "a7b341c14fec0c7a3268d9c08f6bc210c26cbdfe0e578bff25c74781e56c31db"
    end
    on_intel do
      url "https://github.com/behaverse/studyflow-modeler/releases/download/v26.9.23/studyflow-26.9.23-darwin-x64.tar.gz"
      sha256 "0a32dd79ee33e76be19a65cc7406e720d0a03a9642b8bdee6cb4abd9cec3f631"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/behaverse/studyflow-modeler/releases/download/v26.9.23/studyflow-26.9.23-linux-arm64.tar.gz"
      sha256 "b32cd642eae49bbaac6582c014dd40baee00d58dbbe67f6d5b17748cb3ebcebb"
    end
    on_intel do
      url "https://github.com/behaverse/studyflow-modeler/releases/download/v26.9.23/studyflow-26.9.23-linux-x64.tar.gz"
      sha256 "36ff8e0bc4bc97cbf81cee73522c12874d0406065d694ee5ef5c47497e97c256"
    end
  end

  def install
    bin.install "studyflow"
    # The skills (the local runtime among them), found from bin/studyflow as ../libexec/skills.
    libexec.install "skills"
    # The desktop app, served by `studyflow edit` from ../libexec/ui.
    libexec.install "ui"
  end

  test do
    (testpath/"minimal.studyflow").write <<~YAML
      id: brew_test
      definitions:
        targetNamespace: http://bpmn.io/schema/bpmn
      Brew_Test:
        type: bpmn:Process
        name: Brew test
        flowElements:
          Start:
            type: bpmn:StartEvent
          Done:
            type: bpmn:EndEvent
    YAML
    assert_match version.to_s, shell_output("#{bin}/studyflow --version")
    assert_match "OK", shell_output("#{bin}/studyflow validate #{testpath}/minimal.studyflow")
    assert_match "Brew test", shell_output("#{bin}/studyflow info #{testpath}/minimal.studyflow")
    port = free_port
    pid = spawn bin/"studyflow", "edit", "--no-open", "--port", port.to_s, testpath/"minimal.studyflow"
    sleep 2
    assert_match "Studyflow", shell_output("curl -s http://127.0.0.1:#{port}/app")
    assert_match "Brew test", shell_output("curl -s http://127.0.0.1:#{port}/open/minimal.studyflow")
  ensure
    Process.kill("TERM", pid) if pid
  end
end
