# Generated by packages/cli/scripts/package.mjs — do not edit by hand.
class Studyflow < Formula
  desc "Command-line tool for studyflow diagrams"
  homepage "https://github.com/behaverse/studyflow-modeler"
  # No `version`: Homebrew scans 26.9.11 out of the release url, and audit calls a second copy redundant.
  license "MIT"
  # `studyflow run --runtime local` drives the skills in libexec with uv.
  depends_on "uv"

  on_macos do
    on_arm do
      url "https://github.com/behaverse/studyflow-modeler/releases/download/v26.9.11/studyflow-26.9.11-darwin-arm64.tar.gz"
      sha256 "31875035c69603f1fcef8e9512d77d45e3fd1f373b6b15a8158100b218b9992a"
    end
    on_intel do
      url "https://github.com/behaverse/studyflow-modeler/releases/download/v26.9.11/studyflow-26.9.11-darwin-x64.tar.gz"
      sha256 "7933d6b59e0e8acd3ff6b47750bd085a636f6a26731cd65bc8c3d3311dcd9c65"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/behaverse/studyflow-modeler/releases/download/v26.9.11/studyflow-26.9.11-linux-arm64.tar.gz"
      sha256 "638570a257b24ee460ec34847fab83a488633896d3c59f61d833b54b033fe8b9"
    end
    on_intel do
      url "https://github.com/behaverse/studyflow-modeler/releases/download/v26.9.11/studyflow-26.9.11-linux-x64.tar.gz"
      sha256 "3a3831d5c8b42ce48500bf977e77e299bc5177306b3bafc999693282b01afdf7"
    end
  end

  def install
    bin.install "studyflow"
    # The skills (the local runtime among them), found from bin/studyflow as ../libexec/skills.
    libexec.install "skills"
  end

  test do
    (testpath/"minimal.studyflow").write <<~YAML
      id: brew_test
      definitions:
        targetNamespace: http://bpmn.io/schema/bpmn
      Brew_Test:
        type: bpmn:Process
        name: Brew test
        flowElements:
          Start:
            type: bpmn:StartEvent
          Done:
            type: bpmn:EndEvent
    YAML
    assert_match version.to_s, shell_output("#{bin}/studyflow --version")
    assert_match "OK", shell_output("#{bin}/studyflow validate #{testpath}/minimal.studyflow")
    assert_match "Brew test", shell_output("#{bin}/studyflow info #{testpath}/minimal.studyflow")
  end
end
