---
title: "Modeler App"
order: 1
output-file: modeler-app
---

[*Studyflow Modeler*](https://behaverse.org/studyflow-modeler/){.external target="_blank"} is an app to design and execute studyflow diagrams. With modeler, you can visually define every step of your study, from initial conception to subject recruitment, data collection, analysis pipelines, and final reporting.

## Key Features

- Drag-and-drop interface to create studyflow diagrams with nodes representing different studyflow elements.
- Predefined node types for common studyflow components such as cognitive tests, video games, questionnaires, and instructions.
- Export studyflow diagrams as XML, PNG, or SVG.
- Integration with Behaverse Data Server to run studies directly from the modeler app.
- Simulation mode to test and debug diagrams before deployment.

## Getting Started

1. Open the [Modeler app](https://behaverse.org/studyflow-modeler/app){.external target="_blank"} in your web browser.
2. Enter your Behaverse API key to access additional features, or just click "Login" to use the app in guest mode.
3. Use the left palette to drag and drop elements onto the canvas.
4. Select an element to configure its properties in the right sidebar.
5. Connect elements by selecting the connect tools in the left palette. First select the source element and then target element. The type of the connection will depend on the selected elements.
6. Add additional elements and connections to complete your diagram.
7. Save your diagram using the "Save As..." option in the "File" menu. The diagram will be saved as XML file (`*.studyflow`).
8. Alternatively, you can export the diagram as an image using the export options in the "File" menu.

## Simulation Mode

TODO

## Publishing Studies

TODO
