/**
 * `npm run package -w @behaverse/studyflow-cli` build the homebrew and release artifacts for all platforms (or a subset).
 *
 * Output: packages/cli/dist/release/
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { copyFileSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const cliDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repoDir = resolve(cliDir, '../..');
const outDir = resolve(cliDir, 'dist/release');

const { version } = JSON.parse(readFileSync(resolve(cliDir, 'package.json'), 'utf8'));
const repo = process.env.STUDYFLOW_REPO ?? 'behaverse/studyflow-modeler';
const tag = `v${version}`;

/** Bun's cross-compilation targets, and what we call them in an asset name. */
const PLATFORMS = [
  { slug: 'darwin-arm64', bunTarget: 'bun-darwin-arm64', macho: true },
  { slug: 'darwin-x64', bunTarget: 'bun-darwin-x64', macho: true },
  { slug: 'linux-x64', bunTarget: 'bun-linux-x64', macho: false },
  { slug: 'linux-arm64', bunTarget: 'bun-linux-arm64', macho: false },
];

// `--local`: build the host only and write a formula for the local install.
const local = process.argv.includes('--local');
const hostSlug = `${process.platform}-${process.arch}`;
const only = local ? [hostSlug] : process.argv.slice(2).filter((arg) => !arg.startsWith('-'));
const platforms = only.length ? PLATFORMS.filter((p) => only.includes(p.slug)) : PLATFORMS;
if (!platforms.length) throw new Error(`No platform matched: ${only.join(', ')}. Known: ${PLATFORMS.map((p) => p.slug).join(', ')}.`);

// The runners for `studyflow run --runtime local`: the reference runner, its prov module, and the partial runners.
const RUNNERS = readdirSync(resolve(cliDir, 'runners')).filter((name) => /^studyflow-.*\.py$/.test(name));

const sh = (command, args, cwd = repoDir) => execFileSync(command, args, { cwd, stdio: 'inherit' });

sh('npm', ['run', 'build', '-w', '@behaverse/studyflow-cli']);

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const assets = [];
for (const { slug, bunTarget, macho } of platforms) {
  const stage = resolve(outDir, slug);
  mkdirSync(stage, { recursive: true });

  sh('bun', [
    'build', 'dist/studyflow.mjs',
    '--compile',
    `--target=${bunTarget}`,
    // `render` drives a browser; playwright stays a repo-workspace import that fails with an explanation.
    '--external', '@playwright/test',
    `--outfile=${resolve(stage, 'studyflow')}`,
  ], cliDir);

  if (macho && process.platform === 'darwin') {
    sh('codesign', ['--force', '--sign', '-', resolve(stage, 'studyflow')]);
  }

  for (const script of RUNNERS) copyFileSync(resolve(cliDir, 'runners', script), resolve(stage, script));
  copyFileSync(resolve(repoDir, 'LICENSE'), resolve(stage, 'LICENSE'));

  const asset = `studyflow-${version}-${slug}.tar.gz`;
  sh('tar', ['-czf', resolve(outDir, asset), '-C', stage, 'studyflow', ...RUNNERS, 'LICENSE']);
  rmSync(stage, { recursive: true, force: true });

  const sha256 = createHash('sha256').update(readFileSync(resolve(outDir, asset))).digest('hex');
  writeFileSync(resolve(outDir, `${asset}.sha256`), `${sha256}  ${asset}\n`);
  assets.push({ slug, asset, sha256 });
  console.log(`${asset}  ${sha256}`);
}

const urlFor = (asset) => (local
  ? `file://${resolve(outDir, asset)}`
  : `https://github.com/${repo}/releases/download/${tag}/${asset}`);
const blockFor = (slug, indent) => {
  const found = assets.find((a) => a.slug === slug);
  if (!found) return `${indent}# ${slug}: not built in this run`;
  return `${indent}url "${urlFor(found.asset)}"\n${indent}sha256 "${found.sha256}"`;
};

// This repository is the tap: Homebrew reads `Formula/studyflow.rb` from its default branch.
const formula = `# Generated by packages/cli/scripts/package.mjs — do not edit by hand.
class Studyflow < Formula
  desc "Command-line tool for studyflow diagrams"
  homepage "https://github.com/${repo}"
${local
    ? `  version "${version}" # a file:// url gives the scanner nothing to read the version from`
    : /^\d+(\.\d+)+$/.test(version)
      ? `  # No \`version\`: Homebrew scans ${version} out of the release url, and audit calls a second copy redundant.`
      : `  version "${version}" # a pre-release suffix defeats the url scan, which then reads "64" out of "arm64"`}
  license "MIT"
  # \`studyflow run --runtime local\` drives the runners in libexec with uv.
  depends_on "uv"

  on_macos do
    on_arm do
${blockFor('darwin-arm64', '      ')}
    end
    on_intel do
${blockFor('darwin-x64', '      ')}
    end
  end

  on_linux do
    on_arm do
${blockFor('linux-arm64', '      ')}
    end
    on_intel do
${blockFor('linux-x64', '      ')}
    end
  end

  def install
    bin.install "studyflow"
    # The runners, found from bin/studyflow as ../libexec.
    libexec.install Dir["studyflow-*.py"]
  end

  test do
    (testpath/"minimal.studyflow").write <<~YAML
      id: brew_test
      definitions:
        targetNamespace: http://bpmn.io/schema/bpmn
      Brew_Test:
        type: bpmn:Process
        name: Brew test
        flowElements:
          Start:
            type: bpmn:StartEvent
          Done:
            type: bpmn:EndEvent
    YAML
    assert_match version.to_s, shell_output("#{bin}/studyflow --version")
    assert_match "OK", shell_output("#{bin}/studyflow validate #{testpath}/minimal.studyflow")
    assert_match "Brew test", shell_output("#{bin}/studyflow info #{testpath}/minimal.studyflow")
  end
end
`;

writeFileSync(resolve(outDir, 'studyflow.rb'), formula);
if (local) {
  console.log(`\nLocal formula (file:// url) written. Test:`);
  console.log('  brew tap-new --no-git local/studyflow-dev   # once');
  console.log(`  cp ${resolve(outDir, 'studyflow.rb')} "$(brew --repository)/Library/Taps/local/homebrew-studyflow-dev/Formula/"`);
  console.log('  brew install local/studyflow-dev/studyflow');
  console.log('  brew test local/studyflow-dev/studyflow && brew uninstall studyflow');
} else if (platforms.length === PLATFORMS.length) {
  // The formula and the assets come from this one build, so they agree; commit the formula before tagging.
  mkdirSync(resolve(repoDir, 'Formula'), { recursive: true });
  writeFileSync(resolve(repoDir, 'Formula/studyflow.rb'), formula);
  console.log(`\nFormula/studyflow.rb updated for ${tag} (npm run release:cli commits, tags, pushes, and publishes it).`);
} else {
  console.log(`\nPartial build (${platforms.map((p) => p.slug).join(', ')}); Formula/studyflow.rb is untouched.`);
}
