/**
 * `npm run package -w @behaverse/studyflow-cli` build the homebrew and release artifacts for all platforms (or a subset).
 *
 * Output: packages/cli/dist/release/
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const cliDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repoDir = resolve(cliDir, '../..');
const outDir = resolve(cliDir, 'dist/release');

const { version } = JSON.parse(readFileSync(resolve(cliDir, 'package.json'), 'utf8'));
const repo = process.env.STUDYFLOW_REPO ?? 'morteza/studyflow-modeler';
const tag = `v${version}`;

/** Bun's cross-compilation targets, and what we call them in an asset name. */
const PLATFORMS = [
  { slug: 'darwin-arm64', bunTarget: 'bun-darwin-arm64', macho: true },
  { slug: 'darwin-x64', bunTarget: 'bun-darwin-x64', macho: true },
  { slug: 'linux-x64', bunTarget: 'bun-linux-x64', macho: false },
  { slug: 'linux-arm64', bunTarget: 'bun-linux-arm64', macho: false },
];

// `--local`: build the host only and write a formula for the local install.
const local = process.argv.includes('--local');
const hostSlug = `${process.platform}-${process.arch}`;
const only = local ? [hostSlug] : process.argv.slice(2).filter((arg) => !arg.startsWith('-'));
const platforms = only.length ? PLATFORMS.filter((p) => only.includes(p.slug)) : PLATFORMS;
if (!platforms.length) throw new Error(`No platform matched: ${only.join(', ')}. Known: ${PLATFORMS.map((p) => p.slug).join(', ')}.`);

const sh = (command, args, cwd = repoDir) => execFileSync(command, args, { cwd, stdio: 'inherit' });

sh('npm', ['run', 'build', '-w', '@behaverse/studyflow-cli']);

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const assets = [];
for (const { slug, bunTarget, macho } of platforms) {
  const stage = resolve(outDir, slug);
  mkdirSync(stage, { recursive: true });

  sh('bun', [
    'build', 'dist/studyflow.mjs',
    '--compile',
    `--target=${bunTarget}`,
    // `render` drives a browser; playwright stays a repo-workspace import that fails with an explanation.
    '--external', '@playwright/test',
    `--outfile=${resolve(stage, 'studyflow')}`,
  ], cliDir);

  if (macho && process.platform === 'darwin') {
    sh('codesign', ['--force', '--sign', '-', resolve(stage, 'studyflow')]);
  }

  // copy extra scripts
  copyFileSync(resolve(repoDir, 'packages/cli/src/studyflow-run-local.py'), resolve(stage, 'studyflow-run-local.py'));
  copyFileSync(resolve(repoDir, 'packages/cli/src/studyflow-prov.py'), resolve(stage, 'studyflow-prov.py'));
  copyFileSync(resolve(repoDir, 'packages/cli/src/studyflow-python.py'), resolve(stage, 'studyflow-python.py'));
  copyFileSync(resolve(repoDir, 'packages/cli/src/studyflow-reachy.py'), resolve(stage, 'studyflow-reachy.py'));
  copyFileSync(resolve(repoDir, 'LICENSE'), resolve(stage, 'LICENSE'));

  const asset = `studyflow-${version}-${slug}.tar.gz`;
  sh('tar', ['-czf', resolve(outDir, asset), '-C', stage, 'studyflow', 'studyflow-run-local.py', 'studyflow-prov.py', 'studyflow-python.py', 'studyflow-reachy.py', 'LICENSE']);
  rmSync(stage, { recursive: true, force: true });

  const sha256 = createHash('sha256').update(readFileSync(resolve(outDir, asset))).digest('hex');
  writeFileSync(resolve(outDir, `${asset}.sha256`), `${sha256}  ${asset}\n`);
  assets.push({ slug, asset, sha256 });
  console.log(`${asset}  ${sha256}`);
}

const urlFor = (asset) => (local
  ? `file://${resolve(outDir, asset)}`
  : `https://github.com/${repo}/releases/download/${tag}/${asset}`);
const blockFor = (slug, indent) => {
  const found = assets.find((a) => a.slug === slug);
  if (!found) return `${indent}# ${slug}: not built in this run`;
  return `${indent}url "${urlFor(found.asset)}"\n${indent}sha256 "${found.sha256}"`;
};

// Homebrew only discovers formulae in a tap's root `Formula/`
const formula = `# Generated by packages/cli/scripts/package.mjs — do not edit by hand.
class Studyflow < Formula
  desc "Command-line tool for studyflow files: convert, validate, inspect, run"
  homepage "https://github.com/${repo}"
  license "MIT"
${local
    ? `  version "${version}"  # a file:// url gives the scanner nothing to read the version from`
    : `  # No \`version\`: Homebrew scans ${version} out of the release url, and audit calls a second copy redundant.`}

  on_macos do
    on_arm do
${blockFor('darwin-arm64', '      ')}
    end
    on_intel do
${blockFor('darwin-x64', '      ')}
    end
  end

  on_linux do
    on_arm do
${blockFor('linux-arm64', '      ')}
    end
    on_intel do
${blockFor('linux-x64', '      ')}
    end
  end

  def install
    bin.install "studyflow"
    # The runners for \`studyflow run --runtime local\`; found next to the binary, driven by uv.
    libexec.install "studyflow-run-local.py"
    libexec.install "studyflow-prov.py"
    libexec.install "studyflow-python.py"
    libexec.install "studyflow-reachy.py"
  end

  def caveats
    <<~EOS
      convert, validate and info are self-contained: nothing else to install.

      \`studyflow run --runtime local\` executes a study through the runners in
      this keg — studyflow-run-local walks and executes, studyflow-prov records,
      partial runners like studyflow-python and studyflow-reachy execute the elements they claim — all
      driven by uv:
        brew install uv
    EOS
  end

  test do
    (testpath/"minimal.studyflow").write <<~YAML
      id: brew_test
      definitions:
        targetNamespace: http://bpmn.io/schema/bpmn
      Brew_Test:
        type: bpmn:Process
        name: Brew test
        flowElements:
          Start:
            type: bpmn:StartEvent
          Done:
            type: bpmn:EndEvent
    YAML
    assert_match version.to_s, shell_output("#{bin}/studyflow --version")
    assert_match "OK", shell_output("#{bin}/studyflow validate #{testpath}/minimal.studyflow")
    assert_match "Brew test", shell_output("#{bin}/studyflow info #{testpath}/minimal.studyflow")
  end
end
`;

writeFileSync(resolve(outDir, 'studyflow.rb'), formula);
if (local) {
  console.log(`\nLocal formula (file:// url) written. Test:`);
  console.log('  brew tap-new --no-git local/studyflow-dev   # once');
  console.log(`  cp ${resolve(outDir, 'studyflow.rb')} "$(brew --repository)/Library/Taps/local/homebrew-studyflow-dev/Formula/"`);
  console.log('  brew install local/studyflow-dev/studyflow');
  console.log('  brew test local/studyflow-dev/studyflow && brew uninstall studyflow');
} else if (platforms.length === PLATFORMS.length) {
  mkdirSync(resolve(repoDir, 'Formula'), { recursive: true });
  writeFileSync(resolve(repoDir, 'Formula/studyflow.rb'), formula);
  console.log('\nFormula/studyflow.rb updated.');
  console.log(`Release in packages/cli/dist/release/ — upload to ${tag}.`);
} else {
  console.log(`\nPartial build (${platforms.map((p) => p.slug).join(', ')}); Formula/studyflow.rb is still there.`);
}
