/**
 * `npm run package -w @behaverse/studyflow-cli` — the Homebrew release artefacts.
 *
 * Vite bundles the CLI to one ESM file (schemas inlined), then `bun build
 * --compile` welds that file to a Bun runtime, once per platform. The result
 * needs no Node, no npm install, and nothing from this repo. Bun is a build
 * tool here only: it is not in the shipped binary's dependency surface.
 *
 * Writes packages/cli/dist/release/: a tarball and a .sha256 per platform, plus
 * the Homebrew formula pointing at the tag's release assets.
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const cliDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repoDir = resolve(cliDir, '../..');
const outDir = resolve(cliDir, 'dist/release');

const { version } = JSON.parse(readFileSync(resolve(cliDir, 'package.json'), 'utf8'));
const repo = process.env.STUDYFLOW_REPO ?? 'morteza/studyflow-modeler';
const tag = `v${version}`;

/** Bun's cross-compilation targets, and what we call them in an asset name. */
const PLATFORMS = [
  { slug: 'darwin-arm64', bunTarget: 'bun-darwin-arm64', macho: true },
  { slug: 'darwin-x64', bunTarget: 'bun-darwin-x64', macho: true },
  { slug: 'linux-x64', bunTarget: 'bun-linux-x64', macho: false },
  { slug: 'linux-arm64', bunTarget: 'bun-linux-arm64', macho: false },
];

const only = process.argv.slice(2).filter((arg) => !arg.startsWith('-'));
const platforms = only.length ? PLATFORMS.filter((p) => only.includes(p.slug)) : PLATFORMS;
if (!platforms.length) throw new Error(`No platform matched: ${only.join(', ')}. Known: ${PLATFORMS.map((p) => p.slug).join(', ')}.`);

const sh = (command, args, cwd = repoDir) => execFileSync(command, args, { cwd, stdio: 'inherit' });

// The bundle every platform's binary is cut from.
sh('npm', ['run', 'build', '-w', '@behaverse/studyflow-cli']);

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const assets = [];
for (const { slug, bunTarget, macho } of platforms) {
  const stage = resolve(outDir, slug);
  mkdirSync(stage, { recursive: true });

  sh('bun', [
    'build', 'dist/studyflow.mjs',
    '--compile',
    `--target=${bunTarget}`,
    // `render` drives a browser; playwright stays a repo-workspace import that fails with an explanation.
    '--external', '@playwright/test',
    `--outfile=${resolve(stage, 'studyflow')}`,
  ], cliDir);

  // Bun ad-hoc signs its Mach-O output, but re-sign on macOS so appending never leaves an arm64 binary unrunnable.
  if (macho && process.platform === 'darwin') {
    sh('codesign', ['--force', '--sign', '-', resolve(stage, 'studyflow')]);
  }

  // The Python runner rides along so `run --runtime local` works from an installed keg (given `uv`).
  copyFileSync(resolve(repoDir, 'packages/runner-py/studyflow_run.py'), resolve(stage, 'studyflow_run.py'));
  copyFileSync(resolve(repoDir, 'LICENSE'), resolve(stage, 'LICENSE'));

  const asset = `studyflow-${version}-${slug}.tar.gz`;
  sh('tar', ['-czf', resolve(outDir, asset), '-C', stage, 'studyflow', 'studyflow_run.py', 'LICENSE']);
  rmSync(stage, { recursive: true, force: true });

  const sha256 = createHash('sha256').update(readFileSync(resolve(outDir, asset))).digest('hex');
  writeFileSync(resolve(outDir, `${asset}.sha256`), `${sha256}  ${asset}\n`);
  assets.push({ slug, asset, sha256 });
  console.log(`${asset}  ${sha256}`);
}

const urlFor = (asset) => `https://github.com/${repo}/releases/download/${tag}/${asset}`;
const blockFor = (slug, indent) => {
  const found = assets.find((a) => a.slug === slug);
  if (!found) return `${indent}# ${slug}: not built in this run`;
  return `${indent}url "${urlFor(found.asset)}"\n${indent}sha256 "${found.sha256}"`;
};

// Homebrew only discovers formulae in a tap's root `Formula/`, so that is where this lands.
const formula = `# Generated by packages/cli/scripts/package.mjs — do not edit by hand.
class Studyflow < Formula
  desc "Command-line tool for studyflow files: convert, validate, inspect, run"
  homepage "https://github.com/${repo}"
  license "MIT"
  # No \`version\`: Homebrew scans ${version} out of the asset names, and audit calls a second copy redundant.

  on_macos do
    on_arm do
${blockFor('darwin-arm64', '      ')}
    end
    on_intel do
${blockFor('darwin-x64', '      ')}
    end
  end

  on_linux do
    on_arm do
${blockFor('linux-arm64', '      ')}
    end
    on_intel do
${blockFor('linux-x64', '      ')}
    end
  end

  def install
    bin.install "studyflow"
    # The fallback runner for \`studyflow run --runtime local\`; found next to the binary, and driven by uv.
    libexec.install "studyflow_run.py"
  end

  def caveats
    <<~EOS
      convert, validate and info are self-contained: nothing else to install.

      \`studyflow run --runtime local\` executes a study, which needs Python. Either
      install the runner as a companion, the way git finds git-lfs:
        uv tool install studyflow-runner   # puts studyflow-run on your PATH
      or install uv alone, and the copy in this keg is used instead:
        brew install uv
    EOS
  end

  test do
    (testpath/"minimal.studyflow").write <<~YAML
      id: brew_test
      definitions:
        targetNamespace: http://bpmn.io/schema/bpmn
      Brew_Test:
        type: bpmn:Process
        name: Brew test
        flowElements:
          Start:
            type: bpmn:StartEvent
          Done:
            type: bpmn:EndEvent
    YAML
    assert_match version.to_s, shell_output("#{bin}/studyflow --version")
    assert_match "OK", shell_output("#{bin}/studyflow validate #{testpath}/minimal.studyflow")
    assert_match "Brew test", shell_output("#{bin}/studyflow info #{testpath}/minimal.studyflow")
  end
end
`;

writeFileSync(resolve(outDir, 'studyflow.rb'), formula);
if (platforms.length === PLATFORMS.length) {
  mkdirSync(resolve(repoDir, 'Formula'), { recursive: true });
  writeFileSync(resolve(repoDir, 'Formula/studyflow.rb'), formula);
  console.log('\nFormula/studyflow.rb updated.');
} else {
  console.log(`\nPartial build (${platforms.map((p) => p.slug).join(', ')}); Formula/studyflow.rb left alone.`);
}

console.log(`Release assets in packages/cli/dist/release/ — upload them to ${tag}.`);
