export const ICONS = {
  close: 'iconify bi--x-lg',
  closeSmall: 'iconify bi--x',
  crossThin: 'iconify mdi--close',
  caretDown: 'iconify bi--caret-down',
  chevronLeft: 'iconify bi--chevron-left',
  chevronRight: 'iconify bi--chevron-right',
  menu: 'iconify solar--hamburger-menu-linear',
  threeDots: 'iconify fluent--more-horizontal-16-filled',
  search: 'iconify bi--search',
  plus: 'iconify bi--plus',
  plusBox: 'iconify ph--plus-square',
  plusThin: 'iconify mdi--plus',
  pencil: 'iconify bi--pencil',
  gear: 'iconify bi--gear',
  cog: 'iconify ph--gear',
  list: 'iconify bi--list',
  fullscreen: 'iconify bi--fullscreen',
  sidebarExpand: 'iconify tabler--layout-sidebar-right-expand-filled',
  sidebarCollapse: 'iconify tabler--layout-sidebar-right-collapse-filled',
  help: 'iconify bi--patch-question',
  book: 'iconify bi--book',
  arrowLeft: 'iconify bi--arrow-left',
  /* The one polychrome glyph in the app: `iconify-color` paints it as a background
     image, keeping the set's own colours instead of taking `currentColor`. */
  paintBrush: 'iconify-color fluent-color--paint-brush-16',
  arrowRepeat: 'iconify tabler--replace-filled',
  arrowClockwise: 'iconify bi--arrow-clockwise',
  history: 'iconify tabler--history',
  loop: 'iconify ph--arrow-clockwise',
  asterisk: 'iconify mdi--asterisk',
  tilde: 'iconify ph--tilde',

  play: 'iconify bi--play',
  playFill: 'iconify bi--play-fill',
  pause: 'iconify bi--pause-fill',
  stop: 'iconify bi--stop',
  jumpToStart: 'iconify bi--skip-start-fill',
  jumpToEnd: 'iconify bi--skip-end-fill',

  document: 'iconify fluent--document-24-regular',
  folderOpen: 'iconify bi--folder2-open',
  fileNew: 'iconify bi--file-earmark-plus',
  save: 'iconify bi--floppy',
  download: 'iconify bi--download',

  person: 'iconify bi--person',
  peopleTeam: 'iconify fluent--people-team-24-regular',
  handLeft: 'iconify fluent--hand-left-24-regular',
  envelope: 'iconify ph--envelope-simple',
  envelopeOpen: 'iconify ph--envelope-simple-open',
  google: 'iconify bi--google',
  github: 'iconify bi--github',
  branch: 'iconify mdi--source-branch',
  filter: 'iconify mdi--filter-variant',
  copy: 'iconify mdi--content-copy',
  check: 'iconify mdi--check',
  warning: 'iconify bi--exclamation-triangle',
  unlock: 'iconify bi--unlock',
  pin: 'iconify mdi--pin-outline',
  undo: 'iconify material-symbols--undo',
  redo: 'iconify material-symbols--redo',

  table: 'iconify bi--table',
  tableGrid: 'iconify ph--table',
  database: 'iconify fluent--database-16-regular',
  gantt: 'iconify bi--bar-chart-steps',
  script: 'iconify fluent--script-24-regular',
  function: 'iconify ph--function',
  broadcast: 'iconify bi--broadcast-pin',
  checkSquare: 'iconify bi--check2-square',
  checkbox: 'iconify ph--check-square',
  circleOutline: 'iconify mdi--checkbox-blank-circle-outline',

  square: 'iconify fluent--square-16-regular',
  squareDashed: 'iconify mynaui--square-dashed',
  circle: 'iconify fluent--circle-16-regular',
  diamond: 'iconify fluent--diamond-16-regular',
  pentagon: 'iconify mdi--pentagon-outline',
  hexagon: 'iconify tabler--hexagon',

  bpmnSubprocess: 'iconify bpmn--subprocess-collapsed',
  bpmnStartEvent: 'iconify bpmn--start-event-none',
  bpmnIntermediateEvent: 'iconify bpmn--intermediate-event-none',
  bpmnEndEvent: 'iconify bpmn--end-event-none',
  bpmnGatewayXor: 'iconify bpmn--gateway-xor',
  bpmnGatewayOr: 'iconify bpmn--gateway-or',
  bpmnGatewayParallel: 'iconify bpmn--gateway-parallel',
  bpmnGatewayComplex: 'iconify bpmn--gateway-complex',
  bpmnGatewayEventBased: 'iconify bpmn--gateway-eventbased',
  bpmnParticipant: 'iconify bpmn--participant',
  bpmnGroup: 'iconify bpmn--group',
  bpmnCompensationMarker: 'iconify bpmn--compensation-marker',

  /* Context-pad */
  note: 'iconify fluent--comment-text-16-regular',
  arrowUpRight: 'iconify bi--arrow-right',
  trash: 'iconify fluent--delete-16-regular',
  expand: 'iconify fluent--resize-16-regular',
  slash: 'iconify bi--slash-lg',
  swapVertical: 'iconify fluent--person-swap-16-regular',

  /* Text-style bar */
  textBold: 'iconify ph--text-b',
  textItalic: 'iconify ph--text-italic',
  alignLeft: 'iconify ph--text-align-left',
  alignCenter: 'iconify ph--text-align-center',
  alignRight: 'iconify ph--text-align-right',
} as const;

export type IconName = keyof typeof ICONS;
