project:
  type: website
  output-dir: ../dist/docs/
  preview:
    port: 4321
  resources:
    - "assets/**/*"

language: 
  search-text-placeholder: Search

website:
  title: "Studyflow Documentations"
  navbar: false
  sidebar:
    style: docked
    logo-alt: "Studyflow Modeler - Documentations"
    title: "Studyflow Documentations"
    align: center
    pinned: true
    search: true
    footer: |
      <span style='font-size: .7rem; color:gray'>&copy; 2025 xCIT</span>
    contents:
      - file: index.qmd
        title: Introduction
      - auto: "*.qmd"

format:
  html:
    theme:
      - brand
    css: assets/css/styles.css
    toc: false
    grid:
      sidebar-width: 300px