project:
  type: website
  title: Studyflow Documentations
  preview:
    port: 4321
    watch-inputs: true
  resources:
    - "assets/**/*"

language: 
  search-text-placeholder: Search

website:
  navbar: false
  bread-crumbs: true
  page-navigation: true
  sidebar:
    style: docked
    # background: "#f8f8f8"
    border: true
    logo-alt: "Studyflow Modeler - Documentations"
    title: Studyflow Documentations
    align: center
    pinned: true
    search: true
    collapse-level: 1
    footer: |
      <p style='font-size: .75rem' class="text-secondary fst-italic">&copy; 2025 [xCIT](https://xcit.org)</p>
    contents:
      - file: index.qmd
        text: Introduction
      - text: "---"
      - file: getting-started.qmd
      - text: "---"
      - section: Guides
        auto: guides/
      - text: "---"
      - section: Examples
        auto: examples/
      - text: "---"
      - section: Reference
        auto: reference/
      - text: "---"
      - file: roadmap.qmd

format:
  html:
    theme: 
      light: brand
    css: assets/css/styles.css
    respect-user-color-scheme: true
    email-obfuscation: javascript
    toc: false
    toc-location: right
    toc-title: "Contents"
    # link-external-icon: true
    link-external-newwindow: true
    grid:
      sidebar-width: 300px