project:
  type: website
  preview:
    port: 4321
    watch-inputs: true
  resources:
    - "assets/**/*"

language: 
  search-text-placeholder: Search

website:
  title: "Studyflow Documentations"
  navbar: false
  sidebar:
    style: docked
    background: "#f8f8f8"
    border: true
    logo-alt: "Studyflow Modeler - Documentations"
    title: "Studyflow Documentations"
    align: center
    pinned: true
    search: true
    footer: |
      <p style='font-size: .75rem' class="text-secondary fst-italic">&copy; 2025 [xCIT](https://xcit.org)</p>
    contents:
      - file: index.qmd
        title: Introduction
      - auto: "*.qmd"

format:
  html:
    theme:
      - brand
    css: assets/css/styles.css
    toc: false
    grid:
      sidebar-width: 300px