project:
  type: website
  output-dir: ../dist/docs/

website:
  title: "Studyflow"
  sidebar:
    style: "docked"
    search: true
    contents: auto

format:
  html:
    theme:
      - brand
    css: assets/styles.css
    toc: false

