project:
  type: website

website:
  title: "Studyflow"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - studyflow.qmd
      - modeler.qmd

format:
  html:
    theme:
      - brand
    css: styles.css
    toc: false



