project:
  type: manuscript

manuscript:
  article: index.qmd
  meca-bundle: false
format:
  html:
    comments:
      hypothesis: false
  jats: default
  pdf: default

# execute:
#   freeze: true



