project:
  type: website
  output-dir: ../dist/docs

website:
  title: "Studyflow Modeler"
  description: "Documentation for Studyflow and Studyflow Modeler"
  site-url: https://behaverse.org/studyflow-modeler/docs/
  favicon: assets/img/favicon.ico
  llms-txt: true
  search: true
  navbar: false
  bread-crumbs: true
  page-navigation: true
  sidebar:
    id: default
    title: Studyflow Docs
    logo: assets/img/logo.png
    alignment: center
    style: docked
    pinned: true
    collapse-level: 1
    search: true
    footer:  "&copy; 2025 xCIT"
    tools:
      - icon: clock-history
        text: Roadmap
        href: roadmap.qmd
      - icon: github
        href: https://github.com/behaverse/studyflow-modeler
        text: GitHub
    contents:
      - text: Introduction
        href: index.qmd
      - section: Guides
        contents:
          - auto: guides/*.qmd
      - section: Reference
        contents:
          - auto: reference/*.qmd
      - section: Examples
        contents:
          - auto: examples/*.qmd
      - text: ---
      - text: <i>Modeler App</i>
        href: https://behaverse.org/studyflow-modeler/app.html
        icon: box-arrow-up-right
        target: _blank
  open-graph: true

format:
  html:
    theme: default
    css:
      - assets/css/custom.css
      - assets/css/figures.css
    toc: true
    mainfont: "IBM Plex Sans"
    highlight-style: github
