project:
  type: website
  output-dir: ../dist/docs/

website:
  title: "Studyflow"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - studyflow.qmd
      - modeler.qmd

format:
  html:
    theme:
      - brand
    css: assets/styles.css
    toc: false

